/*
 Tappy! - a lightweight normalized tap event. Copyright 2013 @scottjehl, Filament Group, Inc. Licensed MIT */
(function(){function h(c,a){var b=null;return function(){var e=this,d=arguments;clearTimeout(b);b=setTimeout(function(){a.apply(e,d)},c)}}function g(c,a){if("querySelectorAll"in document&&"string"===typeof c){if(a){if(a.jquery){var b=a[0];if(!b)return a}else b=a;return $(b.querySelectorAll(c))}return $(document.querySelectorAll(c))}return $(c,a)}"matchMedia"in window&&window.matchMedia("only all");var p=0<=document.body.className.indexOf("standard-template")?"standard":"office";0==$("#column_right").children().length?
$(document.body).addClass("no-sidebars"):$(document.body).addClass("has-sidebars");(function(c,a,b){var e=function(b){return b.each(function(){function b(b){b.preventDefault();a(b.target).trigger("tap",[b])}function e(a){a.preventDefault();if(f&&f!==a.type)return!1;f=a.type;clearTimeout(g);g=setTimeout(function(){f=null},1E3);if("touchend"===a.type&&15<Math.abs(c.document.body.scrollTop-h))return!1;l&&(d[0].href=l);l=null;b(a)}var d=a(this),f,g,h,l;d.bind("touchstart",function(){h=c.document.body.scrollTop;
d.is("a")&&(l=d[0].href,d[0].href="#")}).bind("touchend",e).bind("click",e)})},d=a.fn.bind;a.fn.bind=function(a,b){/(^| )tap( |$)/.test(a)&&e(this);return d.apply(this,[a,b])}})(this,jQuery);window.throttle=h;window.debounce=function(c,a){var b=null;return function(){b&&clearTimeout(b);var e=arguments;b=setTimeout(function(){a.apply(null,e);b=null},c)}};$("select.autosubmit").on("change",function(){"NULL"!=this.value&&$(this).parents("form").submit()});0=="placeholder"in document.createElement("input")&&
$("input[placeholder]").each(function(){var c=$(this),a=c.attr("placeholder");c.val(a).addClass("placeholder").focus(function(){c.val()==a&&c.val("").removeClass("placeholder")}).blur(function(){""==c.val()&&c.val(a).addClass("placeholder")})});var q={init:function(){var c=!1,a=g("#site-banner"),b=g("#site-banner .expand-menu"),e=null;g("#site-banner a.expand-bttn").bind("tap",function(d){c?(a.removeClass("open"),e=window.setTimeout(function(){b.hide()},500)):(b.show(),window.setTimeout(function(){a.addClass("open")},
50),window.clearTimeout(e));c=!c})}},r={init:function(){function c(){var c=d.scrollTop();200<c?(e&&c+g>m?(b||k.addClass("sticky"),a||k.addClass("visible"),b=!0):(b&&k.removeClass("sticky"),a||k.addClass("visible"),b=!1),a=!0):(b&&k.removeClass("sticky"),a&&k.removeClass("visible"),a=b=!1)}var a=!1,b=!1,e=!0,d=$(window),f=$("#column_two"),g=d.height();if(f.length)var m=f.offset().top+f.height();else f=$(document.body),e=!1;var k=$('<a href="#top" title="Back to Top" id="totop-arrow">Top of Page</a>').appendTo(f);
e&&(d.on("resize",h(400,function(){g=d.height();m=f.offset().top+f.height()})),d.load(function(){m=f.offset().top+f.height()}));c();d.scroll(function(){c()});$('a[href="#top"]').bind("tap",function(a){a.preventDefault();a=d.scrollTop();a=Math.floor(a/3E3*1E3);a=Math.max(200,Math.min(800,a));$("html, body").animate({scrollTop:0},a,"swing")})}},t={init:function(){g(".dropdown-button").each(function(){function c(){g(".dropdown-content").removeClass("open");g(".dropdown-button").removeClass("active")}
var a=$(this),b=this.href.substr(1+this.href.lastIndexOf("#"));var e=g("#"+b);if(0==e.length)return this;a.bind("tap",function(b){b.preventDefault();a.hasClass("active")?c():(c(),a.addClass("active"),e.addClass("open"))})})}},n={table_max_w:0,debounce:function(c,a){var b=null;return function(){b&&clearTimeout(b);var e=arguments;b=setTimeout(function(){a.apply(null,e);b=null},c)}},init:function(){var c=0;$("table").each(function(){var a=$(this);if(a.hasClass("not-responsive"))return!0;if(a.hasClass("table-stack-small")){var b=
$("tr",a).first();if(b.length){var e=b.children("th");if(e.length){b.addClass("thead");var d=[];e.each(function(){d.push($.trim($(this).text()))});$("tr:gt(0)",a).each(function(){$("td",this).each(function(a){a<d.length&&""!=d[a]&&$(this).prepend('<label class="th">'+d[a]+":</label>")})})}}a.wrap('<div class="table-wrap"><div class="table-wrap-inner"></div></div>')}else a.wrap('<div class="table-wrap"><div class="table-wrap-scroll"><div class="table-wrap-inner"></div></div></div>');c++});c&&($(window).on("resize orientationchange",
this.debounce(100,function(){n.updateSizes()})),this.updateSizes())},updateSizes:function(){var c=$("div.table-wrap-inner");if(0==c.length)return!1;if(0==this.table_max_w&&(this.table_max_w=parseInt(c.eq(0).css("max-width"),10),isNaN(this.table_max_w)||0==this.table_max_w)){this.table_max_w=500;try{console.warn("Missing CSS max-width for div.table-wrap-inner!")}catch(a){}}c.css({width:this.table_max_w+"px"});c.each(function(){$(this).parent().removeClass("table-stacked")});c.each(function(){var a=
$(this),b=a.children("table").first();if(b.hasClass("table-stack-small"))var c=a.parent(),d="stacked";else c=a.parent().parent(),d="scroll";b=b.outerWidth();var f=c.outerWidth();"scroll"==d?a.width(b):a.width("100%");b>f?c.addClass("table-"+d):c.removeClass("table-"+d)})}},u={init:function(){var c="sendBeacon"in navigator;$(document.body).on("click","a.ga-outbound-link",function(a){a={eventCategory:"Outbound Links",eventAction:"click",eventLabel:this.href};if(c)a.transport="beacon",ga("send","event",
a);else return ga("send","event",a),setTimeout('document.location = "'+this.href+'"',200),!1})}};(function(){function c(a,b){a.styleSheet?a.styleSheet.cssText=b:a.textContent=b}function a(){if(760<=$(window).width()){var a=document.createElement("style"),b=document.head||document.getElementsByTagName("head")[0];a.type="text/css";b.appendChild(a);c(a,"@media screen and (min-width: 760px) { \n #desktop-menu { display: block ; } \n #mobile-menu { display: none; } \n}");var f=0;$("#desktop-menu").children("ul").children("li").each(function(){f+=
$(this).outerWidth()});b=Math.min(1090,Math.max(f,760));c(a,"@media screen and (min-width: "+b+"px) { \n #desktop-menu { display: block !important; min-width: "+b+"px; } \n #mobile-menu { display: none !important; } \n}");$(window).off("resize.mainmenu orientationchange.mainmenu");return!0}return!1}function b(a){"A"==this.tagName?window.location.href=this.href:"LI"==this.tagName&&(a=$(this).children("a")[0],window.location.href=a.href);return!1}if(0==$("#desktop-menu > ul").length)return console.warn("Primary navigation menu is empty."),
!1;responsiveNav("#mobile-menu-list",{customToggle:"mobile-hamburger"});if("office"==p){if(!a())$(window).on("resize.mainmenu orientationchange.mainmenu",h(100,a));$("#desktop-menu > ul").superfish({autoArrows:!1,delay:400}).off("MSPointerDown.superfish touchend.superfish mousedown.superfish").on("MSPointerDown.superfish  mousedown.superfish touchstart.superfish","a",b)}})();$(document).ready(function(){t.init();q.init();$("table").each(function(){$("tr:nth-child(even)",this).addClass("even");3<$("tr",
this).length&&$(this).addClass("table-striped")});n.init();r.init();u.init()})})();

/**
 * Search Box
 * Targets new Coveo search page
 */
$(document).ready(function() {
    $('.uta-search-form').each(function() {
		// Send query to new Coveo Search page
		var $form = $(this);
		var $searchBox = $('.uta-search-box', $form);
		
		$form.submit(function(e) {
			e.preventDefault();
			var keyword = $searchBox.val();
			window.location.href = 'https://www.uta.edu/search#q=' + encodeURIComponent(keyword);
		});
	});
});
